import { Router } from "express";
import { requireAdmin } from "./admin";

const router = Router();

router.get("/admin/news-manager", requireAdmin, (_req, res) => {
  res.type("html").send(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>إدارة الأخبار | QPN</title><style>body{margin:0;background:#f5f7fb;color:#172033;font-family:system-ui,-apple-system,"Segoe UI",sans-serif}.wrap{max-width:1100px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:center;gap:16px}.brand{font-size:28px;font-weight:900}.muted{color:#667085}.card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:20px;margin-top:20px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:700px){.grid{grid-template-columns:1fr}}label{display:block;font-weight:700;margin:10px 0 6px}input,textarea,select{width:100%;padding:12px;border:1px solid #d0d5dd;border-radius:10px;font:inherit;box-sizing:border-box}textarea{min-height:180px;resize:vertical}.actions{display:flex;gap:10px;margin-top:16px;flex-wrap:wrap}button{border:0;border-radius:10px;padding:12px 16px;font-weight:800;cursor:pointer}.primary{background:#172033;color:white}.secondary{background:#eef2f6}.danger{background:#fff1f2;color:#b42318}.status{padding:8px 12px;border-radius:999px;background:#ecfdf3;color:#067647;font-weight:700;font-size:12px}.item{border-top:1px solid #eaecf0;padding:16px 0}.item:first-child{border-top:0}.item h3{margin:0 0 8px}.row{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.error{color:#b42318;margin-top:10px}.ok{color:#067647;margin-top:10px}</style></head><body><main class="wrap"><div class="top"><div><div class="brand">إدارة الأخبار</div><div class="muted">Qatar People News — Web Admin</div></div><button id="back" class="secondary">لوحة التحكم</button></div><section class="card"><h2>إنشاء خبر</h2><form id="form"><div class="grid"><div><label>العنوان</label><input id="title" required maxlength="240"></div><div><label>التصنيف</label><select id="category"><option value="">بدون تصنيف</option></select></div><div><label>صورة الغلاف</label><input id="cover" type="url" placeholder="https://..."></div><div><label>رابط الفيديو</label><input id="video" type="url" placeholder="https://..."></div></div><label>الملخص</label><input id="excerpt" maxlength="500"><label>المحتوى</label><textarea id="content" required></textarea><div class="grid"><div><label>الحالة</label><select id="status"><option value="draft">مسودة</option><option value="published">نشر</option></select></div><div><label>نوع الخبر</label><select id="breaking"><option value="false">عادي</option><option value="true">عاجل</option></select></div></div><div class="actions"><button class="primary">حفظ الخبر</button><button type="button" id="refresh" class="secondary">تحديث القائمة</button></div><div id="message"></div></form></section><section class="card"><div class="row"><h2>الأخبار الحالية</h2><span class="status" id="count">0</span></div><div id="list">جارٍ التحميل...</div></section></main><script>
const $=id=>document.getElementById(id); const message=(text,ok=false)=>{ $('message').textContent=text; $('message').className=ok?'ok':'error'; };
async function categories(){const r=await fetch('/api/admin/news/categories');if(r.status===401){location.href='/api/admin';return}const d=await r.json();$('category').innerHTML='<option value="">بدون تصنيف</option>'+d.data.map(x=>'<option value="'+x.id+'">'+escapeHtml(x.name)+'</option>').join('');}
async function load(){const r=await fetch('/api/admin/news');if(r.status===401){location.href='/api/admin';return}const d=await r.json();$('count').textContent=d.data.length+' خبر';$('list').innerHTML=d.data.length?d.data.map(x=>'<article class="item"><div class="row"><div><h3>'+escapeHtml(x.title)+'</h3><div class="muted">'+escapeHtml(x.status)+' · '+(x.isBreaking?'عاجل':'عادي')+' · '+x.views+' مشاهدة</div></div><button class="danger archive" data-id="'+x.id+'">أرشفة</button></div></article>').join(''):'لا توجد أخبار بعد';}
function escapeHtml(s){return String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
$('list').addEventListener('click',async e=>{const button=e.target.closest('.archive');if(!button)return;if(!confirm('أرشفة هذا الخبر؟'))return;const r=await fetch('/api/admin/news/'+button.dataset.id,{method:'DELETE'});if(!r.ok){message('تعذر أرشفة الخبر');return}await load();message('تمت الأرشفة',true);});
$('form').onsubmit=async e=>{e.preventDefault();message('');const body={title:$('title').value,content:$('content').value,excerpt:$('excerpt').value,coverImageUrl:$('cover').value,videoUrl:$('video').value,categoryId:$('category').value,status:$('status').value,isBreaking:$('breaking').value==='true'};const r=await fetch('/api/admin/news',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){message(d.error||'تعذر حفظ الخبر');return}e.target.reset();await load();message('تم حفظ الخبر بنجاح',true)};
$('refresh').onclick=load;$('back').onclick=()=>location.href='/api/admin';categories();load();
</script></body></html>`);
});

export default router;
